export const CONSTANTS = {
  headerTitle: "🎧 WuYun with Chords !",
  rightPanel: {
    chordsLabel: "伴奏生成",
    uploadLabel: "参考生成",
    mixLabel: "混合生成",
    TaskLabel: "任务",
  },
  mixPanel: {
    mixingModeChooseLabel: "🧬 混合模式",
    mixingUploadLabel: "上传 A/B",
    mixingSelectionLabel: "选区 A/B",
    sourcesLabel: "📎 参考来源",
    pickMidiALabel: "选择 A MIDI",
    pickMidiBLabel: "选择 B MIDI",
    pickSelectionALabel: "用当前选区作为 A",
    pickSelectionBLabel: "用当前选区作为 B",
    bpmLabel: "BPM",
    barsLabel: "小节数",
    uploadHint: "提示：上传模式下请先选两首 MIDI；和弦格子数量以“小节数”为准。",
    selectionHint: "提示：先在时间条上框选一个小节范围，再点 A / B 把当前选区捕获为参考。",
    genBtnLabel: "生成 mix set",
    resultsLabel: "🚀 混合结果",
    noTaskLabel: "尚无混合结果",
    noTaskHint: "先点“生成 mix set”，然后在 Task Tab 里看进度；成功后这里会出现可选的 mix MIDI。",
    applySelectionLabel: "覆盖选区",
  },
  chordMode: {
    pianoLabel: "🎹 钢琴",
    guitarLabel: "🎸 吉他",
    bassLabel: "🎸 贝斯",
    instrumentLabel: "🎷 乐器选择 (可多选)",
    chordGenLabel: "🎶 和弦行进指定",
    clearBtnLabel: "清除选区",
    genBtnLabel: "生成",
    resultTab: {
      headLabel: "🚀 生成结果",
      piano: "钢琴",
      guitar: "吉他",
      bass: "贝斯",
      noTaskYet: "尚无结果",
      noTaskLabel: "该乐器还没有生成记录",
      noTaskHint: "提示：先点“生成”，然后在 Task Tab 看任务进度；成功后这里会出现可选的 MIDI",
      updateSelection: "覆盖选区",
    },
  },
  chordProgression: {
    emptyHint: "先选择小节范围，然后这里会出现对应数量的和弦格子",
  },
  barSelectionInfo: {
    emptyHint: "未选中任何小节 (请在时间条上拖拽选择)",
    label: "🎼 选中小节信息",
  },
  uploadMode: {
    uploadLabel: "📤 上传 MIDI",
    midiAnalyzeLabel: "🖥️ MIDI 解析结果",
    midiAnalyzeHint: "尚未选择文件。选择 MIDI 后，这里会显示 MIDI 解析结果",
    importMidiToTrackBtnLabel: "导入 MIDI 至新轨道",
    chooseMidiBtnLabel: "上传文件",
    clearBtnLabel: "清除",
    instrumentLabel: "🎷 乐器选择 (單選)",
    refMidiGenBtnLabel: "基於上傳生成",
    refSelectionGenBtnLabel: "基於選區生成",
    refSourceLabel: "📝 參考來源",
    refSelectionLabel: "參考選區",
    refSelectionHint: "以選中的小節內容當作參考",
    refMidiLabel: "參考上傳 MIDI",
    refMidiHint: "以下方上傳的 MIDI 當作參考",
  },
}

